name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "Dockerfile"
      - ".github/workflows/docker-image.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker Hub

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag khub/root-crawler:latest
        docker tag khub/root-crawler:latest khub/root-crawler:${{ github.sha }}

    - name: Push Docker image
      run: |
        docker push khub/root-crawler:latest
        docker push khub/root-crawler:${{ github.sha }}
